# Generated by Django 4.2 on 2023-04-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
