# Generated by Django 4.2 on 2023-05-26 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userprofile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
